name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android NDK
      uses: android-actions/setup-ndk@v3
      with:
        ndk-version: '25.2.9519653'

    - name: Build Android
      env:
        _BUILD_CFG: ${{ matrix.abi }} out/android/${{ matrix.abi }}/Release
        NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        chmod +x ./build.android
        ./build.android

    - name: Upload SO artifacts
      uses: actions/upload-artifact@v4
      with:
        name: libortextensions-${{ matrix.abi }}
        path: out/android/${{ matrix.abi }}/Release/**/*.so
        if-no-files-found: error

    - name: Upload AAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: onnxruntime-extensions-${{ matrix.abi }}.aar
        path: out/android/${{ matrix.abi }}/Release/aar_out/*.aar
        if-no-files-found: warn
